### ISSUE TITLE
ponto . em padronizar_numeros 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/enderecobr#37]
`enderecobr::padronizar_numeros('1.028')`
o resultado é `128`

`enderecobr::padronizar_numeros(1.028)`
o resultado é `1`

em ambos os casos, eu esperaria que o resultados fosse `1028`. Faz sentido?

**Comment by dhersz** [comment]
O caso `enderecobr::padronizar_numeros(1.028)` tá certo... Tem que lembrar que número no R não tem ponto. Isso aí é equivalente ao número real 1,028. Vou ver o primeiro caso.

**Comment by dhersz** [comment]
Done https://github.com/ipeaGIT/enderecobr/commit/e816ba6c687033a0f27ba7f441214669391f9417.

**Comment by rafapereirabr** [comment]
aqui no R em ingles, o ponto é o separador decimal neh. Entao `1.028` é o numero mil e vinte e oito. 

```
gsub("\\.", "", 1.028)
>1028
```

**Comment by dhersz** [comment]
A sua frase não faz sentido hehe. Se o ponto é o separador decimal, então 1.028 é 1,028. Aí ele arredonda pra 1.

Esse caso aí do gsub é porque a função faz a conversão automática de número pra string, então ele na verdade tá considerando "1.028". No caso da padronizar_numeros(), os números não são tratados como strings a não ser que sejam passados assim.
